activation_checkpoint_layers:
 - MixtralDecoderLayer

# Refer to https://github.com/pytorch/xla/issues/6379 for backward optimization barrier info.
optimization_barrier_layers:
 - MixtralDecoderLayer
