defaults:
  - _self_  # refers to this config file
  - sharding: llama-fsdp  # refers to sharding/llama-fsdp.yaml
  - remat: llama-scan  # refers to remat/llama-scan.yaml


model_id: llama-3-test
model_class: llama.LlamaForCausalLM  # Used to import the model from this class
pretrained_model: null

vocab_size: 32001
bos_token_id: 1
eos_token_id: 2

hidden_size: 128
num_hidden_layers: 5

num_attention_heads: 4
num_key_value_heads: 2

intermediate_size: 256
hidden_act: silu

max_position_embeddings: 2048
rope_theta: 10000.0

attention_dropout: false
attention_bias: false

initializer_range: 0.02
rms_norm_eps: 1.0e-05

# choose attention_kernel from: [flash_attention, splash_attention, null]
attention_kernel: flash_attention
